export type UniversityType = 'PUBLIC' | 'PRIVATE' | 'INTERNATIONAL';
export type Category = 'General' | 'Engineering' | 'Science & Technology' | 'Medical' | 'Agricultural' | 'Specialized' | 'Textile' | 'Architecture';

export type University = {
  id: string; name: string; shortName: string; type: UniversityType; category: Category[];
  division: string; district: string; city: string; address: string; latitude: number; longitude: number;
  establishedYear?: number; logo: string; description: string; website: string; maps: string;
  source: string; lastVerified: string;
};

const logo = (initials: string, color: string) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="50" fill="${color}"/><circle cx="50" cy="50" r="38" fill="none" stroke="white" stroke-opacity=".75" stroke-width="2"/><text x="50" y="58" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700" fill="white">${initials}</text></svg>`)}`;

export const universities: University[] = [
  {id:'du',name:'University of Dhaka',shortName:'DU',type:'PUBLIC',category:['General'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'Shahbag, Dhaka 1000',latitude:23.733,longitude:90.395,establishedYear:1921,logo:logo('DU','#176b87'),description:'Bangladesh’s oldest modern university and a major centre for teaching, research and public life.',website:'https://www.du.ac.bd',maps:'https://maps.google.com/?q=University+of+Dhaka',source:'Official university website',lastVerified:'September 2026'},
  {id:'buet',name:'Bangladesh University of Engineering and Technology',shortName:'BUET',type:'PUBLIC',category:['Engineering','Architecture'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'Palashi, Dhaka 1000',latitude:23.726,longitude:90.392,establishedYear:1962,logo:logo('BUET','#155e75'),description:'A leading public institution focused on engineering, architecture and urban planning.',website:'https://www.buet.ac.bd',maps:'https://maps.google.com/?q=BUET',source:'Official university website',lastVerified:'September 2026'},
  {id:'ju',name:'Jahangirnagar University',shortName:'JU',type:'PUBLIC',category:['General'],division:'Dhaka',district:'Dhaka',city:'Savar',address:'Savar, Dhaka 1342',latitude:23.879,longitude:90.268,establishedYear:1970,logo:logo('JU','#1f7a68'),description:'A residential public university known for its green campus, research and liberal arts tradition.',website:'https://juniv.edu',maps:'https://maps.google.com/?q=Jahangirnagar+University',source:'Official university website',lastVerified:'September 2026'},
  {id:'nsu',name:'North South University',shortName:'NSU',type:'PRIVATE',category:['General','Science & Technology'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'Bashundhara, Dhaka 1229',latitude:23.815,longitude:90.425,establishedYear:1992,logo:logo('NSU','#9a6430'),description:'Bangladesh’s first private university, offering broad programs from a modern Dhaka campus.',website:'https://www.northsouth.edu',maps:'https://maps.google.com/?q=North+South+University',source:'Official university website',lastVerified:'September 2026'},
  {id:'bracu',name:'BRAC University',shortName:'BRACU',type:'PRIVATE',category:['General','Science & Technology'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'Kha 224, Pragati Sarani, Dhaka 1212',latitude:23.780,longitude:90.407,establishedYear:2001,logo:logo('BRAC','#b06c3b'),description:'A research-oriented private university with strengths in development, technology and the arts.',website:'https://www.bracu.ac.bd',maps:'https://maps.google.com/?q=BRAC+University',source:'Official university website',lastVerified:'September 2026'},
  {id:'aiub',name:'American International University-Bangladesh',shortName:'AIUB',type:'PRIVATE',category:['Engineering','General'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'Kuril, Dhaka 1229',latitude:23.822,longitude:90.427,establishedYear:1994,logo:logo('AIUB','#7c5c8d'),description:'An English-medium private university with a strong emphasis on business, computing and engineering.',website:'https://www.aiub.edu',maps:'https://maps.google.com/?q=AIUB',source:'Official university website',lastVerified:'September 2026'},
  {id:'cu',name:'University of Chittagong',shortName:'CU',type:'PUBLIC',category:['General'],division:'Chattogram',district:'Chattogram',city:'Hathazari',address:'Hathazari, Chattogram',latitude:22.460,longitude:91.780,establishedYear:1966,logo:logo('CU','#256b63'),description:'A large public university on a hillside campus serving the southeast of Bangladesh.',website:'https://cu.ac.bd',maps:'https://maps.google.com/?q=University+of+Chittagong',source:'Official university website',lastVerified:'September 2026'},
  {id:'cuet',name:'Chittagong University of Engineering and Technology',shortName:'CUET',type:'PUBLIC',category:['Engineering'],division:'Chattogram',district:'Chattogram',city:'Raozan',address:'Raozan, Chattogram 4349',latitude:22.461,longitude:92.115,establishedYear:1968,logo:logo('CUET','#1b6b72'),description:'A public engineering university with a residential campus in Raozan, Chattogram.',website:'https://www.cuet.ac.bd',maps:'https://maps.google.com/?q=CUET',source:'Official university website',lastVerified:'September 2026'},
  {id:'kuet',name:'Khulna University of Engineering & Technology',shortName:'KUET',type:'PUBLIC',category:['Engineering'],division:'Khulna',district:'Khulna',city:'Khulna',address:'Fulbarigate, Khulna 9203',latitude:22.899,longitude:89.503,establishedYear:1967,logo:logo('KUET','#236a7a'),description:'A public technological university specializing in engineering and applied science.',website:'https://www.kuet.ac.bd',maps:'https://maps.google.com/?q=KUET',source:'Official university website',lastVerified:'September 2026'},
  {id:'ruet',name:'Rajshahi University of Engineering & Technology',shortName:'RUET',type:'PUBLIC',category:['Engineering'],division:'Rajshahi',district:'Rajshahi',city:'Rajshahi',address:'Kazla, Rajshahi 6204',latitude:24.363,longitude:88.624,establishedYear:1964,logo:logo('RUET','#2d6670'),description:'A public engineering university known for technical education and applied research.',website:'https://www.ruet.ac.bd',maps:'https://maps.google.com/?q=RUET',source:'Official university website',lastVerified:'September 2026'},
  {id:'sust',name:'Shahjalal University of Science and Technology',shortName:'SUST',type:'PUBLIC',category:['Science & Technology'],division:'Sylhet',district:'Sylhet',city:'Sylhet',address:'Kumargaon, Sylhet 3114',latitude:24.919,longitude:91.831,establishedYear:1987,logo:logo('SUST','#2f7a73'),description:'A public science and technology university with a strong culture of innovation and research.',website:'https://www.sust.edu',maps:'https://maps.google.com/?q=SUST',source:'Official university website',lastVerified:'September 2026'},
  {id:'bau',name:'Bangladesh Agricultural University',shortName:'BAU',type:'PUBLIC',category:['Agricultural'],division:'Mymensingh',district:'Mymensingh',city:'Mymensingh',address:'Mymensingh 2202',latitude:24.721,longitude:90.426,establishedYear:1961,logo:logo('BAU','#357358'),description:'The country’s leading agricultural university, supporting food and rural development research.',website:'https://bau.edu.bd',maps:'https://maps.google.com/?q=Bangladesh+Agricultural+University',source:'Official university website',lastVerified:'September 2026'},
  {id:'ru',name:'University of Rajshahi',shortName:'RU',type:'PUBLIC',category:['General'],division:'Rajshahi',district:'Rajshahi',city:'Rajshahi',address:'Motihar, Rajshahi 6205',latitude:24.364,longitude:88.628,establishedYear:1953,logo:logo('RU','#6c7541'),description:'A comprehensive public university with a large research and teaching community.',website:'https://www.ru.ac.bd',maps:'https://maps.google.com/?q=University+of+Rajshahi',source:'Official university website',lastVerified:'September 2026'},
  {id:'jnu',name:'Jagannath University',shortName:'JnU',type:'PUBLIC',category:['General'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'9-10 Chittaranjan Avenue, Dhaka 1100',latitude:23.708,longitude:90.407,establishedYear:2005,logo:logo('JnU','#6b5b84'),description:'A public university at the historic heart of Old Dhaka with a growing research profile.',website:'https://jnu.ac.bd',maps:'https://maps.google.com/?q=Jagannath+University',source:'Official university website',lastVerified:'September 2026'},
  {id:'ewu',name:'East West University',shortName:'EWU',type:'PRIVATE',category:['General','Science & Technology'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'A/2 Jahurul Islam Avenue, Dhaka 1212',latitude:23.769,longitude:90.426,establishedYear:1996,logo:logo('EWU','#8b6547'),description:'A private university in Aftabnagar offering programs across business, sciences and engineering.',website:'https://www.ewubd.edu',maps:'https://maps.google.com/?q=East+West+University+Bangladesh',source:'Official university website',lastVerified:'September 2026'},
  {id:'iubat',name:'International University of Business Agriculture and Technology',shortName:'IUBAT',type:'PRIVATE',category:['General','Agricultural'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'4 Embankment Drive Road, Dhaka 1230',latitude:23.881,longitude:90.386,establishedYear:1991,logo:logo('IUBAT','#7a7845'),description:'A private university with an interdisciplinary focus spanning business, agriculture and technology.',website:'https://iubat.edu',maps:'https://maps.google.com/?q=IUBAT',source:'Official university website',lastVerified:'September 2026'},
  {id:'uap',name:'University of Asia Pacific',shortName:'UAP',type:'PRIVATE',category:['Engineering','Architecture'],division:'Dhaka',district:'Dhaka',city:'Dhaka',address:'74/A Green Road, Dhaka 1205',latitude:23.752,longitude:90.385,establishedYear:1996,logo:logo('UAP','#89654c'),description:'A private university recognized for architecture, engineering and interdisciplinary programs.',website:'https://uap-bd.edu',maps:'https://maps.google.com/?q=University+of+Asia+Pacific',source:'Official university website',lastVerified:'September 2026'},
  {id:'nstu',name:'Noakhali Science and Technology University',shortName:'NSTU',type:'PUBLIC',category:['Science & Technology'],division:'Chattogram',district:'Noakhali',city:'Noakhali',address:'Sonapur, Noakhali 3814',latitude:22.790,longitude:91.101,establishedYear:2006,logo:logo('NSTU','#31746e'),description:'A public science and technology university serving the coastal Noakhali region.',website:'https://nstu.edu.bd',maps:'https://maps.google.com/?q=NSTU',source:'Official university website',lastVerified:'September 2026'},
  {id:'pstu',name:'Patuakhali Science and Technology University',shortName:'PSTU',type:'PUBLIC',category:['Science & Technology','Agricultural'],division:'Barishal',district:'Patuakhali',city:'Dumki',address:'Dumki, Patuakhali 8602',latitude:22.464,longitude:90.383,establishedYear:2000,logo:logo('PSTU','#477461'),description:'A public university combining agricultural education with science and technology.',website:'https://www.pstu.ac.bd',maps:'https://maps.google.com/?q=PSTU',source:'Official university website',lastVerified:'September 2026'}
];

export const divisions = ['All divisions', ...Array.from(new Set(universities.map(u => u.division)))];
export const categories: Category[] = ['General','Engineering','Science & Technology','Medical','Agricultural','Specialized','Textile','Architecture'];
