import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { categories, divisions, universities, University, UniversityType } from './data';
import { bangladeshPath } from './bangladeshBoundary';
import './styles.css';

const palette: Record<UniversityType, string> = { PUBLIC:'#6fd5ce', PRIVATE:'#e5a86a', INTERNATIONAL:'#bba8ef' };
const typeLabel: Record<UniversityType,string> = { PUBLIC:'Public', PRIVATE:'Private', INTERNATIONAL:'International' };
const divisionLines = ['M176 64 L185 106 L172 151 L187 199 L172 250','M248 50 L235 93 L243 137 L229 181 L230 263','M123 110 L167 119 L219 108 L278 78','M111 190 L158 184 L218 193 L305 213','M129 91 L143 141 L132 220','M193 51 L219 108 L218 193 L216 269'];

function project(lat:number, lon:number) { return { x: 225 + (lon - 90.1) * 71, y: 252 - (lat - 20.6) * 71 }; }
function initials(name:string) { return name.split(' ').map(w=>w[0]).slice(0,2).join(''); }

function App() {
  const [query,setQuery] = useState(''); const [type,setType] = useState<UniversityType|'ALL'>('ALL'); const [category,setCategory] = useState('All categories'); const [division,setDivision] = useState('All divisions');
  const [selected,setSelected] = useState<University|null>(null); const [zoom,setZoom] = useState(1); const [offset,setOffset] = useState({x:0,y:0}); const [filtersOpen,setFiltersOpen] = useState(false); const [aboutOpen,setAboutOpen] = useState(false);
  const filtered = useMemo(()=>universities.filter(u => { const hay=`${u.name} ${u.shortName} ${u.district} ${u.division} ${u.city}`.toLowerCase(); return (!query || hay.includes(query.toLowerCase())) && (type==='ALL'||u.type===type) && (category==='All categories'||u.category.includes(category as never)) && (division==='All divisions'||u.division===division); }),[query,type,category,division]);
  const counts = useMemo(()=>({public:filtered.filter(u=>u.type==='PUBLIC').length, private:filtered.filter(u=>u.type==='PRIVATE').length, international:filtered.filter(u=>u.type==='INTERNATIONAL').length}),[filtered]);
  const reset = () => { setQuery(''); setType('ALL'); setCategory('All categories'); setDivision('All divisions'); setSelected(null); setZoom(1); setOffset({x:0,y:0}); };
  const focus = (u:University) => { const p=project(u.latitude,u.longitude); setSelected(u); setZoom(2.15); setOffset({x:310-p.x*1.15,y:250-p.y*1.15}); };
  const handleWheel=(e:React.WheelEvent)=>setZoom(z=>Math.max(.82,Math.min(3.4,z+(e.deltaY<0?.16:-.16))));
  const mapStyle={transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`};

  return <main className="app-shell">
    <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <header className="topbar">
      <button className="brand" onClick={reset} aria-label="Return to Bangladesh overview"><span className="brand-mark"><span/></span><span><b>ATLAS</b><em>BD</em><small>UNIVERSITY INTELLIGENCE</small></span></button>
      <div className="top-actions"><button className="nav-link active">Explore</button><button className="nav-link" onClick={()=>setAboutOpen(true)}>About</button><div className="live"><i/>LIVE ATLAS</div></div>
    </header>
    <section className="search-wrap"><div className="search-box"><span className="search-icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search university, city, district…" aria-label="Search universities"/><kbd>⌘ K</kbd></div>{query && <div className="search-results">{filtered.slice(0,5).map(u=><button key={u.id} onClick={()=>focus(u)}><span className="result-dot" style={{background:palette[u.type]}}/><span><b>{u.name}</b><small>{u.shortName} · {u.city}</small></span><span>↗</span></button>)}{!filtered.length&&<p>No universities found in the atlas.</p>}</div>}</section>
    <section className="hero-copy"><p className="eyebrow"><span/> GEOGRAPHIC INTELLIGENCE / 01</p><h1>Explore the<br/><strong>university landscape.</strong></h1><p className="intro">A living atlas of higher education across Bangladesh.<br/>Zoom in to discover where ideas take root.</p></section>
    <section className="map-stage" onWheel={handleWheel} aria-label="Interactive map of Bangladesh">
      <div className="map-grid"/><div className="map-label label-north">NORTH / 26°N</div><div className="map-label label-east">EAST / 92°E</div>
      <svg className="map-svg" viewBox="0 0 430 330" role="img" aria-label="Stylized Bangladesh geographic outline"><defs><filter id="glow"><feGaussianBlur stdDeviation="2.5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="land" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#123b49"/><stop offset="1" stopColor="#0d2836"/></linearGradient></defs><g className="map-transform" style={mapStyle}><path className="land-shadow" d={bangladeshPath}/><path className="land-shape" d={bangladeshPath}/><g className="division-lines">{divisionLines.map((d,i)=><path d={d} key={i}/>)}</g>{filtered.map((u,i)=>{const p=project(u.latitude,u.longitude); const compact=zoom<1.45; return <g key={u.id} className={`marker ${selected?.id===u.id?'selected':''}`} transform={`translate(${p.x} ${p.y})`} onClick={()=>focus(u)} tabIndex={0} role="button" aria-label={`Open ${u.name}`}><circle className="marker-halo" r={compact?6:9} fill={palette[u.type]}/><circle className="marker-core" r={compact?2.4:4.5} fill={palette[u.type]}/>{!compact&&<><circle className="marker-ring" r="12" stroke={palette[u.type]}/><foreignObject x="-15" y="-47" width="30" height="30"><div className="mini-logo" style={{borderColor:palette[u.type]}}>{initials(u.shortName)}</div></foreignObject><foreignObject x="-56" y="15" width="112" height="30"><div className="marker-name">{u.shortName}</div></foreignObject></>}</g>})}</g></svg>
      <div className="map-depth"/><div className="map-caption"><span className="crosshair">✣</span><span><b>BANGLADESH</b><small>DELTA REGION / 147,570 KM²</small></span></div>
      <div className="zoom-controls"><button onClick={()=>setZoom(z=>Math.min(3.4,z+.25))} aria-label="Zoom in">＋</button><div className="zoom-value">{Math.round(zoom*100)}%</div><button onClick={()=>setZoom(z=>Math.max(.82,z-.25))} aria-label="Zoom out">−</button></div>
      <button className="home-control" onClick={reset} aria-label="Reset map">◎ <span>OVERVIEW</span></button>
      <div className="map-scale"><span>0</span><i/><span>100 km</span></div>
    </section>
    <aside className="left-rail"><button className={`rail-button ${filtersOpen?'is-active':''}`} onClick={()=>setFiltersOpen(v=>!v)}><span>☷</span> FILTERS <b>{(type!=='ALL'?1:0)+(category!=='All categories'?1:0)+(division!=='All divisions'?1:0)}</b></button>{filtersOpen&&<div className="filter-card"><div className="filter-head"><span>MAP FILTERS</span><button onClick={reset}>RESET</button></div><label>University type</label><div className="segmented">{(['ALL','PUBLIC','PRIVATE'] as const).map(t=><button className={type===t?'active':''} onClick={()=>setType(t)} key={t}>{t==='ALL'?'All':typeLabel[t as UniversityType]}</button>)}</div><label>Category</label><select value={category} onChange={e=>setCategory(e.target.value)}><option>All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><label>Division</label><select value={division} onChange={e=>setDivision(e.target.value)}>{divisions.map(d=><option key={d}>{d}</option>)}</select></div>}</aside>
    <aside className="stats-card"><div className="stats-label"><span className="pulse"/> ATLAS INDEX <small>UPDATED 09.26</small></div><div className="total-stat"><strong>{filtered.length}</strong><span>universities<br/>mapped</span></div><div className="stat-row"><span><i style={{background:palette.PUBLIC}}/>PUBLIC</span><b>{counts.public}</b></div><div className="stat-row"><span><i style={{background:palette.PRIVATE}}/>PRIVATE</span><b>{counts.private}</b></div><div className="stat-row"><span><i style={{background:palette.INTERNATIONAL}}/>INTERNATIONAL</span><b>{counts.international}</b></div><div className="stats-foot">Showing {filtered.length} of {universities.length} verified locations</div></aside>
    <div className="legend"><span className="legend-title">SIGNAL TYPE</span>{(['PUBLIC','PRIVATE','INTERNATIONAL'] as UniversityType[]).map(t=><span key={t}><i style={{background:palette[t]}}/>{typeLabel[t]}</span>)}</div>
    {selected&&<div className="profile-overlay" onClick={()=>setSelected(null)}><aside className="profile-panel" onClick={e=>e.stopPropagation()}><button className="close-panel" onClick={()=>setSelected(null)}>×</button><div className="profile-top"><div className="profile-logo" style={{borderColor:palette[selected.type],color:palette[selected.type]}}>{initials(selected.shortName)}</div><div><span className="profile-type" style={{color:palette[selected.type]}}>{typeLabel[selected.type]} / {selected.category[0]}</span><h2>{selected.name}</h2><p>{selected.shortName} <span>·</span> {selected.city}, Bangladesh</p></div></div><div className="profile-line"/><p className="profile-description">{selected.description}</p><div className="profile-grid"><div><small>ESTABLISHED</small><b>{selected.establishedYear||'—'}</b></div><div><small>DISTRICT</small><b>{selected.district}</b></div><div><small>DIVISION</small><b>{selected.division}</b></div><div><small>LOCATION</small><b>{selected.latitude.toFixed(3)}° N</b></div></div><div className="profile-address"><small>CAMPUS ADDRESS</small><span>⌖ {selected.address}</span></div><div className="profile-actions"><a href={selected.website} target="_blank" rel="noreferrer">Official website <span>↗</span></a><a className="secondary" href={selected.maps} target="_blank" rel="noreferrer">View on map <span>↗</span></a></div><div className="source-note"><span>◈</span><span>Data source: {selected.source}<br/>Last checked: {selected.lastVerified}</span></div></aside></div>}
    {aboutOpen&&<div className="about-overlay" onClick={()=>setAboutOpen(false)}><div className="about-card" onClick={e=>e.stopPropagation()}><button className="close-panel" onClick={()=>setAboutOpen(false)}>×</button><p className="eyebrow"><span/> ABOUT ATLAS BD</p><h2>The geography of<br/><strong>possibility.</strong></h2><p>Atlas BD is an interactive geographic atlas of universities across Bangladesh — designed to make the country’s education landscape easier to see, explore and understand.</p><div className="about-meta"><span>168</span><small>universities in<br/>the national atlas</small><span>08</span><small>divisions across<br/>Bangladesh</small></div></div></div>}
    <footer><span>© 2026 ATLAS BD</span><span>BUILT FOR THE CURIOUS <b>·</b> DATA WITH CONTEXT</span></footer>
  </main>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
